_target_: src.models.simple_conv_net.SimpleConvNet

defaults:
  - _self_
  - _base_model_config.yaml   # general, model independent, parameters

dim: 64
kernel_sizes: [9, 7, 5, 3]
residual: True
net_normalization: "batch_norm"
dropout: 0.0