_target_: src.utilities.lr_scheduler.LambdaWarmUpCosineScheduler
verbosity_interval: 0
warm_up_steps: 200
max_decay_steps: 2500
lr_start: 5e-4
lr_max: 1e-3
lr_min: 5e-6

# warm_up_steps: 1000
#max_decay_steps: 50000
#lr_start: 0.001
#lr_max: 0.1
#lr_min: 0.0001