# @package _global_

# to execute this module run:
# python run.py module=forecasting_multi_horizon_time_conditioned

defaults:
  - _base_multi_horizon_config.yaml
  - _self_

module:
  _target_: src.experiment_types.forecasting_multi_horizon.MultiHorizonForecastingTimeConditioned

model:
  with_time_emb: True   # time embedding needed for continuous time conditioning
