# THIS FILE HAS BEEN AUTOGENERATED. To update:
# 1. modify the `_deps` dict in setup.py
# 2. run `make deps_table_update``
deps = {
    "black": "black~=23.1",
    "dask": "dask",
    "einops": "einops",
    "hf-doc-builder": "hf-doc-builder>=0.3.0",
    "hydra-core": "hydra-core",
    "isort": "isort>=5.5.4",
    "netCDF4": "netCDF4",
    "numpy": "numpy",
    "omegaconf": "omegaconf",
    "pytest": "pytest",
    "pytorch-lightning": "pytorch-lightning>=2.0",
    "rich": "rich",
    "ruff": "ruff>=0.0.241",
    "regex": "regex!=2019.12.17",
    "requests": "requests",
    "tensordict": "tensordict",
    "torch": "torch>=1.8",
    "torchmetrics": "torchmetrics==0.11.4",
    "urllib3": "urllib3",
    "wandb": "wandb",
    "xarray": "xarray",
    "xskillscore": "xskillscore",
}
